name: Model training with Live Metrics in Studio
on:
  pull_request:
jobs:
  train:
    runs-on: ubuntu-latest
    name: Train model and report results
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup environment
        uses: ./.github/actions/setup_environment

      - name: Train model
        env:
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          # https://studio.iterative.ai/api/live is the prod default
          STUDIO_ENDPOINT: ${{ secrets.STUDIO_ENDPOINT }}
          DVCLIVE_LOGLEVEL: DEBUG
        run: dvc exp run

      - name: Report results
        run: |
          dvc metrics diff main --show-md >> report.md
          npm exec -- cml comment create report.md
          npm exec -- cml pr --rebase "dvc.lock" "params.yaml" "dvclive"
